
title: "   Samer Labban" # your name (or website title) here
logo: "/images/svc_pose.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Autonomous & ADAS Control Algorithm Developer with a focus on Perception & Localization
  <br><br>
  <a href="https://www.linkedin.com/in/samer-labban-7b932372/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
