
title: Samer Labban # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Autonomous & ADAS Control Algorithm Developer 
  <br><br>
  President of the Autonomous Vehicles Club at Oakland University
  <br><br>
  Mechatronics Engineer experienced with development, implementation, and testing of processing and control algorithms for LIDAR, Radar, Camera, and a variety of sensors that are used in current Autonomous and Advanced Drive Assistance Systems, with a secondary focus on Electric Motor design for high performance applications. Skilled at bridging the multi-disciplinary gap
  between the sensor hardware and software processing through strong teamwork and effective communication skills.
  <br><br>
  <a href="https://www.linkedin.com/in/samer-labban-7b932372/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
