
title:       Samer Labban # your name (or website title) here
logo: "/images/Boom_headshot.png =20x20" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Autonomous & ADAS Control Algorithm Developer 
  <br><br>
  President of the Autonomous Vehicles Club at Oakland University
  <br><br>
  I'm a Mechatronics Engineer with demonstrated experience with the development of data processing, state estimation, and control algorithms for GPS/GNSS, LIDAR, Radar, Camera, and a variety of sensors that are used in current Autonomous and Advanced Drive Assistance Systems. In addition, I have a secondary focus on Electric Motor and PCB design. 
  Accompanied with a degree in Mechanical Engineering, my skills shine when bridging the multi-disciplinary gap between hardware and software through strong teamwork and effective communication skills.
  <br><br>
  <a href="https://www.linkedin.com/in/samer-labban-7b932372/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
